name: Update Arbitrage Algorithm

on:
  push:
    branches: [ main ]

env:
  ECR_REPOSITORY: arbitrage-sports-betting
  IMAGE_TAG: latest
  PLATFORM: linux/arm64
  LAMBDA_FUNCTION_NAME: run-arbitrage-algo

jobs:
  build:
    name: Build ECR Img, Update Lambda Fct
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker buildx
      uses: docker/setup-buildx-action@v2

    - name: Remove ECR Image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      run: |
        aws ecr batch-delete-image \
        --repository-name $ECR_REPOSITORY \
        --image-ids imageTag=$IMAGE_TAG

    - name: Build and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      run: |
        docker build --platform=$PLATFORM -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

    - name: Update Lambda Function
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      run: |
        aws lambda update-function-code \
        --function-name $LAMBDA_FUNCTION_NAME \
        --image-uri $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG